name: Bug Issue
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["Ospos CI3", "Ospos CI4"]
assignees:
  - none
body:
  - type: markdown
    attributes:
      value: |
        "Bug reports indicate that something is not working as intended. Please include as much detail as possible and submit a separate bug report for each problem. Do not include personal identifying information such as email addresses or encryption keys." 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true 
  - type: dropdown
    id: version
    attributes:
      label: OpensourcePOS Version
      description: What version of our software are you running?
      options:
        - CI3
        - CI4
      default: 0
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: Php Version
	  multiple: true
      description: Php Version?
      options:
        - Php-7.4 or higher
        - Php-8 not supported in CI3
		- Php-8.1
		- Php-8.2
		- Php-8.3
		- Other
      default: 0
    validations:
      required: true   
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: servers
    attributes:
      label: System Information Report (optional)
      description: Copy and paste from OSPOS > Configuration > Setup & Conf > Setup & Conf?
      placeholder: Web Server and database used
      value: "Web Server and database used!"
    validations:
      required: true        
  - type: checkboxes
    id: terms
    attributes:      
      description: By submitting this issue, you agree that you have not modified this version of OSPOS
      options:
        - label: I agree this has not been modified
          required: true
